hostDB = 127.0.0.1
dbDB = sd
userDB = postgres
passwordDB = SD2024
portDB = 15432

HttpURL = http://localhost:8001

brokerhost = tcp://localhost:1883
brokertopic = Trabalho2SD

API_username = Administrador
API_password = trabalho2SD
