spring.datasource.url=jdbc:postgresql://localhost:5432/TrabalhoTW
spring.datasource.username=joaotiago
spring.datasource.password=joaotiago
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.platform=postgres
spring.jpa.hibernate.ddl-auto=update
